name: Cypress Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: mxgIOz3xWepIJJAiVw34hyDF
        with:
          vercel_project_id: 'prj_Q5WiLZY7AU1kkZPt5axluoNaJI31'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config: baseUrl='https://${{ steps.vercel_preview_url.outputs.preview_url }}'
